name: Doctests
on: push

jobs:
  assignments:
    runs-on: ubuntu-20.04
    container: python:3.10.3

    strategy:
      fail-fast: false
      matrix:
        directory:
          - advanced
          - basics
          - data-science
          - database
          - design-patterns
          - devops
          #- django
          - dragon
          - fastapi
          - gui
          - install
          - intermediate
          #- machine-learning
          #- matplotlib
          #- network
          - numpy
          - oop
          - pandas

    steps:
      - name: Download GIT repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r requirements-cicd.txt

      - name: Test chapter listings
        run: sphinx-build -a -E -j auto --color -b doctest ${{ matrix.directory }} /tmp/

      - name: Run tests for assignments
        run: find ${{ matrix.directory }} -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' \;
