name: Doctests
on: push

jobs:

  Chapter:
    runs-on: ubuntu-20.04
    container: python:3.10.4
    strategy:
      fail-fast: false
      matrix:
        directory:
          - about
          - advanced
          - basics
          - data-science
          - database
          - design-patterns
          - devops
          - django
          - dragon
          - fastapi
          - gui
          - install
          - intermediate
          - machine-learning
          - matplotlib
          - network
          - numpy
          - oop
          - pandas
          - stdlib
    steps:
      - name: Download GIT repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r ${{ matrix.directory }}/requirements.txt

      - name: Run Doctests
        run: python make.py --doctest ${{ matrix.directory }}
