name: Doctests
on: push

jobs:

  Everything:
    runs-on: ubuntu-20.04
    container: python:3.10.4
    steps:
      - uses: actions/checkout@v2
      - run: python run.py --install
      - run: python run.py --doctest

  Chapter:
    runs-on: ubuntu-20.04
    container: python:3.10.4
    strategy:
      fail-fast: false
      matrix:
        directory:
          - about
          - advanced
          - basics
          - data-science
          - database
          - design-patterns
          - devops
          - django
          - dragon
          - fastapi
          - gui
          - install
          - intermediate
          - machine-learning
          - matplotlib
          - network
          - numpy
          - oop
          - pandas
          - stdlib
    steps:
      - uses: actions/checkout@v2
      - run: python run.py --install ${{ matrix.directory }}
      - run: python run.py --doctest ${{ matrix.directory }}
