name: Doctests
on: push

jobs:

  Assignments:
    runs-on: ubuntu-20.04
    container: python:3.10.4
    strategy:
      fail-fast: false
      matrix:
        directory:
          - advanced
          - basics
          - data-science
          - database
          - design-patterns
          - devops
          - django
          - dragon
          - fastapi
          - gui
          - intermediate
          - machine-learning
          - matplotlib
          - network
          - numpy
          - oop
          - pandas
    steps:
      - name: Download GIT repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r ${{ matrix.directory }}/requirements.txt
      - name: Tests assignments
        run: python make.py --test-py ${{ matrix.directory }}
      - name: Count assignments tests
        run: find . -not \( -path "./.venv-py310" -prune \) -name '*.py' |xargs grep '>>>' |wc -l

  Listings:
    runs-on: ubuntu-20.04
    container: python:3.10.4
    strategy:
      fail-fast: false
      matrix:
        directory:
          - advanced
          - basics
          - data-science
          #- database
          - design-patterns
          - devops
          #- django
          #- dragon
          #- fastapi
          #- gui
          - intermediate
          #- machine-learning
          #- matplotlib
          #- network
          - numpy
          - oop
          - pandas
    steps:
      - name: Download GIT repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r ${{ matrix.directory }}/requirements.txt
      - name: Count listing tests
        run: find . -not \( -path "./.venv-py310" -prune \) -name '*.rst' |xargs grep '>>>' |wc -l
      - name: Test listings
        run: python make.py --test-rst ${{ matrix.directory }}
